version: '3.8'
services:
  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6379:6379'
  limiter:
    build: .
    restart: always
    ports:
      # Note this must be changed if you modify the server port
      - '8080:8080'