name: Rate Limiter Test Suite

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Build
      run: make build
    - name: Test
      run: make test
    - name: Clean
      run: make clean
    - name: Wipe Cache
      run: make wipe-cache